import Head from 'next/head';
import { FC } from 'react';
import { NavBar } from '../NavBar';
import styles from './MainLayout.module.css';

interface Props {   
    children: JSX.Element | JSX.Element[];
}


export const MainLayouts = ({ children }: Props ) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>HomePage - Anel G.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
    
            <NavBar />
    
            <main className={styles.main}>

                { children }
            
            </main>
     
        </div>
    )
} 
